Add files via upload

diff --git a/scripts/hardupdate b/scripts/hardupdate
--- a/scripts/hardupdate
+++ b/scripts/hardupdate
@@ -1,41 +1,64 @@
-#update package from experimental-unstable-testing-current
-#usage: getpack "package1 package2..." max_level #1-testing, 2-unstable, 3-experimental
-getpack() {
-  pack=$1
-  local maxlvl="${2:-0}"
-  if [ $maxlvl -ge 3 ] && apt-get -sqq -t experimental install $pack 2>/dev/null | grep -qE "Inst ($(echo "$pack" | tr ' ' '|'))"; then
-    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" -t experimental install $pack
-  elif [ $maxlvl -ge 2 ] && apt-get -sqq -t unstable install $pack 2>/dev/null | grep -qE "Inst ($(echo "$pack" | tr ' ' '|'))"; then
-    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" -t unstable install $pack
-    if [ $maxlvl -ge 3 ]; then
-      DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" -t experimental install $pack
-    fi
-  elif [ $maxlvl -ge 1 ] && apt-get -sqq -t testing install $pack 2>/dev/null | grep -qE "Inst ($(echo "$pack" | tr ' ' '|'))"; then
-    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" -t testing install $pack
-    if [ $maxlvl -ge 2 ]; then
-      DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" -t unstable install $pack
-    fi
-    if [ $maxlvl -ge 3 ]; then
-      DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" -t experimental install $pack
-    fi
+#usage: tryinstall mypackage 0/1/2/3 install/reinstall
+tryinstall() {
+  local pack=$1
+  local lvl="${2:-0}"
+  if [ $lvl = 0 ]; then
+    lvl=
+  elif [ $lvl = 1 ]; then
+    lvl="-t testing "
+  elif [ $lvl = 2 ]; then
+    lvl="-t unstable "
+  elif [ $lvl = 3 ]; then
+    lvl="-t experimental "
+  fi
+  local opr="${3:-install}"
+  if DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" $lvl$opr $pack >"$LOG" 2>&1; then
+    echo "Success: $pack $lvl"
+    return 0
   else
-    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" install $pack
+    echo "Fail: $pack $lvl"
+    return 1
   fi
 }
-
-#reinstall package from experimental-unstable-testing-current
-#usage: forcepack "package1 package2..." max_level #1-testing, 2-unstable, 3-experimental
-forcepack() {
+LOG=$(mktemp)
+trap 'rm -f "$LOG"' EXIT
+#update package from experimental-unstable-testing-current
+#usage: getpack "package1 package2..." max_level operation #level:1-testing, 2-unstable, 3-experimental; operation:install/reinstall
+getpack() {
   local pack=$1
   local maxlvl="${2:-0}"
-  DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" reinstall $pack
-  if [ $maxlvl -ge 1 ]; then
-    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" -t testing reinstall $pack
-  fi
-  if [ $maxlvl -ge 2 ]; then
-    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" -t unstable reinstall $pack
-  fi
-  if [ $maxlvl -ge 3 ]; then
-    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confnew" -o Dpkg::Options::="--force-overwrite" -t experimental reinstall $pack
-  fi
+  local opr="${3:-install}"
+  local i=0
+  while [ $i -le 3 ]; do
+    if [ $i -gt $maxlvl ]; then
+      exit 0
+    fi
+    local idep=0
+    local prev_pkg=
+    while true; do
+      echo "" >"$LOG"
+      if tryinstall "$pack" "$i" "$opr"; then
+        break
+      else
+        if ! grep -q 'Depends:.*but .* is to be installed' "$LOG" || [ $idep -gt $maxlvl ]; then
+          cat "$LOG"
+          exit 1
+        else
+          conflict_pkg=$(grep -oP '^\s*\K\S+(?=\s*: Depends:)' "$LOG" | head -n1)
+          if [ "$conflict_pkg" != "$prev_pkg" ]; then
+            idep=0
+            prev_pkg=$conflict_pkg
+          else
+            idep=$((idep + 1))
+            if [ $idep -gt 3 ]; then
+              cat "$LOG"
+              exit 1
+            fi
+          fi
+          getpack "$conflict_pkg" $idep install
+        fi
+      fi
+    done
+    i=$((i +1))
+  done
 }
